// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerAirPollution.Model;

#nullable disable

namespace AirPollutionPrediction.Migrations
{
    [DbContext(typeof(AirPollutionDbContext))]
    [Migration("20230721075734_Zmiana struktury tabeli InputData")]
    partial class ZmianastrukturytabeliInputData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirPollutionPrediction.Model.InputData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DzieńRoku")
                        .HasColumnType("int");

                    b.Property<int>("DzieńTygodnia")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<double>("MinimalnaTemperaturaDobowa")
                        .HasColumnType("float");

                    b.Property<double>("RodzajOpadu")
                        .HasColumnType("float");

                    b.Property<double>("RóznicaMaksymalnejIMinimalnejTemperatury")
                        .HasColumnType("float");

                    b.Property<string>("Station_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Station_Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("SumaOpaduDzień")
                        .HasColumnType("float");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("ValueCat")
                        .HasColumnType("int");

                    b.Property<double>("ŚredniaDobowaPrędkośćWiatru")
                        .HasColumnType("float");

                    b.Property<double>("ŚredniaDobowaWilgotnośćWzględna")
                        .HasColumnType("float");

                    b.Property<double>("ŚredniaDoboweCiśnienieNaPoziomieStacji")
                        .HasColumnType("float");

                    b.Property<double>("ŚredniaTemperaturaDobowa")
                        .HasColumnType("float");

                    b.Property<double>("ŚrednieDoboweZachmurzenieOgólne")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("InputData", (string)null);
                });

            modelBuilder.Entity("ServerAirPollution.Model.Record", b =>
                {
                    b.Property<int>("Id_sql")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_sql"));

                    b.Property<double>("CiśnienieNaPoziomieStacji")
                        .HasColumnType("float");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<double>("PrędkośćWiatru")
                        .HasColumnType("float");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Station_Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("SumaOpaduDzień")
                        .HasColumnType("float");

                    b.Property<double>("TemperaturaDobowa")
                        .HasColumnType("float");

                    b.Property<string>("ValueCatNo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueCatO3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueCatPm10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueCatPm25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueCatSo2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValueNo2")
                        .HasColumnType("float");

                    b.Property<double>("ValueO3")
                        .HasColumnType("float");

                    b.Property<double>("ValuePm10")
                        .HasColumnType("float");

                    b.Property<double>("ValuePm25")
                        .HasColumnType("float");

                    b.Property<double>("ValueSo2")
                        .HasColumnType("float");

                    b.Property<double>("WilgotnośćWzględna")
                        .HasColumnType("float");

                    b.Property<double>("ZachmurzenieOgólne")
                        .HasColumnType("float");

                    b.HasKey("Id_sql");

                    b.ToTable("Record", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
